<?php
/**
 * Created by PhpStorm.
 * User: zvinger
 * Date: 20.12.17
 * Time: 16:05
 */

namespace Zvinger\BaseClasses\app\models\work\user\object;

use yii\db\ActiveQuery;

class VendorUserQuery extends ActiveQuery
{
    public function byToken($token)
    {
        return $this->joinWith('userBearerTokens')->andWhere(['token'=>$token]);
    }

    /**
     * @param null $db
     * @return VendorUserObject
     */
    public function one($db = NULL)
    {
        return parent::one($db); // TODO: Change the autogenerated stub
    }

    /**
     * @param null $db
     * @return VendorUserObject[]
     */
    public function all($db = NULL)
    {
        return parent::all($db); // TODO: Change the autogenerated stub
    }
}