<?php
/**
 * Created by PhpStorm.
 * User: amorev
 * Date: 06.02.2019
 * Time: 11:04
 */

namespace Zvinger\BaseClasses\app\graphql;


use GraphQL\Error\Debug;
use GraphQL\GraphQL;
use Obvu\Modules\Api\Admin\submodules\crud\graphql\schema\Types;
use yii\base\InvalidArgumentException;
use yii\filters\auth\HttpBearerAuth;
use yii\helpers\Json;
use Zvinger\BaseClasses\api\controllers\BaseApiController;
use Zvinger\BaseClasses\app\graphql\base\context\BaseGraphQLContext;

class GraphQLController extends BaseApiController
{
    public $modelClass = '';

    /**
     * @var callable
     */
    public $getQuery = null;

    /**
     * @var callable
     */
    public $getMutation = null;

    /**
     * @var callable
     */
    public $getContext = null;

    /**
     * @inheritdoc
     */
    protected function verbs()
    {
        return [
            'index' => ['POST'],
        ];
    }

    public function behaviors()
    {
        $old = parent::behaviors();
        $behaviors = [];
        $behaviors['authenticator'] = [
            'class' => HttpBearerAuth::class,
            'optional' => ['index'],
        ];

        return array_merge($old, $behaviors);
    }

    public function actions()
    {
        return [];
    }

    public function beforeAction($action)
    {
        if (empty($this->getQuery) || !is_callable($this->getQuery)) {
            throw new \Exception('->getQuery is null or not callable');
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    public function actionIndex()
    {
        // сразу заложим возможность принимать параметры
        // как через MULTIPART, так и через POST/GET

        $query = \Yii::$app->request->get('query', \Yii::$app->request->post('query'));
        $variables = \Yii::$app->request->get('variables', \Yii::$app->request->post('variables'));
        $operation = \Yii::$app->request->get('operation', \Yii::$app->request->post('operation', null));

        if (empty($query)) {
            $rawInput = file_get_contents('php://input');
            $input = json_decode($rawInput, true);
            $query = $input['query'];
            $variables = isset($input['variables']) ? $input['variables'] : [];
            $operation = isset($input['operation']) ? $input['operation'] : null;
        }

        // библиотека принимает в variables либо null, либо ассоциативный массив
        // на строку будет ругаться

        if (!empty($variables) && !is_array($variables)) {
            try {
                $variables = Json::decode($variables);
            } catch (InvalidArgumentException $e) {
                $variables = null;
            }
        }

        // создаем схему и подключаем к ней наши корневые типы

        $schema = new \GraphQL\Type\Schema(
            [
                'query' => ($this->getQuery)(),
                'mutation' => is_callable($this->getMutation) ? ($this->getMutation)() : null,
            ]
        );
        $myErrorHandler = function (array $errors, callable $formatter) {
            \Yii::error('GraphQL Error:'.json_encode($errors), 'graphql');

            return array_map($formatter, $errors);
        };
        $context = $this->getContext ? ($this->getContext)() : new BaseGraphQLContext();
        if (!($context instanceof BaseGraphQLContext)) {
            throw new \Exception("Context is not ".BaseGraphQLContext::class.' variable');
        }
        // огонь!
        $cache = \Yii::$app->cache;
        try {
            $result = GraphQL::executeQuery(
                $schema,
                $query,
                null,
                $context,
                empty($variables) ? null : $variables,
                empty($operation) ? null : $operation
            )
                ->setErrorsHandler($myErrorHandler)
                ->toArray(YII_DEBUG ? (Debug::INCLUDE_DEBUG_MESSAGE | Debug::INCLUDE_TRACE) : false);
        } catch (GraphQLSchemaException $e) {
            \Yii::error('query executed - '.$query);
            \Yii::error($e->getMessage());
            if (YII_ENV_DEV) {
                throw $e;
            } else {
                \Yii::$app->telegram->message('admin', $e->getMessage());

                return $cache->get('cached.result.gql.'.md5($query));
            }
        }
        $cache->set('cached.result.gql.'.md5($query), $result, 0);

        return $result;
    }
}
