<?php

namespace Zvinger\BaseClasses\app\components\data\miscInfo\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use Zvinger\BaseClasses\app\models\work\user\object\VendorUserObject;

/**
 * This is the model class for table "user_misc_info".
 *
 * @property int $id
 * @property int $object_id
 * @property int $object_type
 * @property string $key
 * @property string $value
 * @property int $json
 * @property int $created_at
 * @property int $updated_at
 *
 */
class BaseVendorMiscInfoObject extends ActiveRecord
{
    /**
     * @var ActiveRecord
     */
    public $objectClass;

    public static $objectType;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%data_misc_info}}';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::class
        ];
    }


    public function beforeSave($insert)
    {
        if (empty($this->object_type)) {
            $this->object_type = static::$objectType;
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['object_id', 'created_at', 'updated_at'], 'integer'],
            [['value'], 'string'],
            [['key'], 'string', 'max' => 100],
            [['json'], 'boolean'],
            [['object_type', 'object_id', 'key'], 'unique', 'targetAttribute' => ['object_type', 'object_id', 'key']],
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getObject()
    {
        return $this->hasOne($this->objectClass::className(), ['id' => 'object_id']);
    }


    /**
     * @inheritdoc
     * @return BaseVendorUserMiscInfoQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new BaseVendorUserMiscInfoQuery(get_called_class());
    }
}
